server:
  port: 8069
spring:
  application:
    name: pdrw
  datasource:
    url: jdbc:postgresql://localhost:5432/pdrw_db
    username: pdrw
    password: pdrwadmin
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show_sql: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: db/changelog/db.changelog-master.yml
    default-schema: public
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


application:
  config:
    alert-url: http://185.244.50.227:5000/send_message
    alert-key: kWQYKdwtI2450aX7xGmj