version: '4'
services:
  front:
    image: maxdevdoc/fpf-frontend:0.0.0.2
    ports:
      - "4200:80"
  nginx:
    image: nginx:1.27.0
    ports:
      - "8089:80"
    depends_on:
      - front
  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_DB: "pdrw-db"
      POSTGRES_USER: "pdrw"
      POSTGRES_PASSWORD: "pdrwadmin"
    ports:
      - "5432:5432"
  back:
    image: shevajoker/pdrw:0.0.0.4
    build:
      context: .
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/pdrw-db"
      POSTGRES_USER: "pdrw"
      POSTGRES_PASSWORD: "pdrwadmin"
    ports:
      - "8069:8069"
    depends_on:
      - postgres