version: '4'
services:
  front:
    image: maxdevdoc/fpf-frontend:0.0.0.5
    ports:
      - "8080:80"
  postgres:
    image: postgres:16.0
    container_name: postgresdb
    environment:
      POSTGRES_DB: "pdrw_db"
      POSTGRES_USER: "pdrw"
      POSTGRES_PASSWORD: "pdrwadmin"
    ports:
      - "5432:5432"
  back:
    image: shevajoker/pdrw:0.0.0.4
    build:
      context: .
    container_name: back
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/pdrw_db"
      POSTGRES_USER: "pdrw"
      POSTGRES_PASSWORD: "pdrwadmin"
    ports:
      - "8069:8069"
    depends_on:
      - postgres