version: "3.9"
services:
  postgres:
    image: postgres:16.0
#    container_name: postgres
    environment:
      POSTGRES_DB: "pdrw_db"
      POSTGRES_USER: "pdrw"
      POSTGRES_PASSWORD: "pdrwadmin"
    ports:
      - "5432:5432"